export const counties = [
    "Anderson",
    "Bledsoe",
    "Blount",
    "Bradley",
    "Campbell",
    "Cannon",
    "Clay",
    "Coffee",
    "Cumberland",
    "Dekalb",
    "Fentress",
    "Franklin",
    "Grundy",
    "Hamilton",
    "Jackson",
    "Knox",
    "Loudon",
    "Marion",
    "McMinn",
    "Meigs",
    "Monroe",
    "Morgan",
    "Overton",
    "Pickett",
    "Polk",
    "Putnam",
    "Roane",
    "Rhea",
    "Scott",
    "Sequatchie",
    "Sevier",
    "Smith",
    "Van Buren",
    "Warren",
    "White"
  ];
  